openapi: 3.0.3
info:
  title: STD23085 - TD2 Meals
  version: '1.0.3'
servers:
  - url: https://localhost.std23085.com
paths:
  /meals:
    get:
      summary: Retrieve a list of meals
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: true
          description: The page number for pagination.
        - in: query
          name: pageSize
          schema:
            type: integer
          required: true
          description: The number of items per page.
      responses:
        200:
          description: List of meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    post:
      summary: Create a new meal
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/CreateMeal'
        required: true
        description: An array of meal objects to create.
      responses:
        200:
          description: List of created meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    put:
      summary: Update existing meals
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/Meal'
        required: true
        description: An array of meal objects to update.
      responses:
        200:
          description: List of updated meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
    delete:
      summary: Delete meals
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                $ref: '#/components/schemas/MealIdentifier'
        required: true
        description: An array of meal identifiers to delete.
      responses:
        200:
          description: List of deleted meals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Meal'
components:
  schemas:
    Meal:
      allOf:
        - $ref: '#/components/schemas/MealIdentifier'
        - $ref: '#/components/schemas/CreateMeal'
    MealIdentifier:
      type: object
      properties:
        id:
          type: string
          description: The unique identifier of the meal.
    CreateMeal:
      type: object
      properties:
        name:
          type: string
          description: The name of the meal.
        price:
          type: number
          format: float
          description: The price of the meal.
